name: main

on:
  push:
    branches:
      - main

jobs:
  job1:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.9', '3.11']
    steps:
      - uses: actions/checkout@v4
      - name: install dependencies
        run: sudo apt install pip flake8
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
      - name: use flake8
        run: flake8
      - name: use unittest
        run: python -m unittest
  job2:
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: ['3.9', '3.10', '3.11']
    steps:
      - uses: actions/checkout@v4
      - name: setup up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version}}
      - name: install dependencies
        run: python -c pip install flake8
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
      - name: use flake8
        run: flake8
      - name: use unittest
        run: python -m unittest